name: base_bloc_cubit_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+102

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  get_it: ^9.0.5
  equatable: ^2.0.7
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_remote_config: ^6.1.1
  firebase_crashlytics: ^5.0.4
  lottie: ^3.3.2
  flutter_svg: ^2.2.2
  lib_ads_rikko_flutter:
    git:
      # url: git@github.com:rikkoteam/libads_flutter.git
      url: https://github.com/rikkoteam/libads_flutter.git
      ref: main
  lib_iap:
    git:
      url: https://github.com/tranduytung0966882567/lib_iap.git
      ref: main
  shared_preferences: ^2.5.3
  app_settings: ^6.1.1
  connectivity_plus: ^6.1.5
  flutter_spinkit: ^5.2.2
  dio: ^5.9.0
  auto_route: ^10.2.1
  auto_route_generator: ^10.2.6
  image_picker: ^1.2.1
  logger: ^2.6.2
  injectable: ^2.6.0
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  path_provider: ^2.1.5
  upgrader: ^12.3.0
  url_launcher: ^6.3.2
  device_info_plus: ^12.2.0
  oktoast: ^3.4.0
  freezed_annotation: ^3.1.0
  share_plus: ^12.0.1
  in_app_review: ^2.0.11
  permission_handler: ^12.0.1
  marquee: ^2.3.0
  pdfrx: ^2.2.16

  file_picker: ^10.3.6
  flutter_inner_shadow: ^0.0.1
  pdf: ^3.11.3
  cunning_document_scanner:
    path: packages/cunning_document_scanner-master
  fluttertoast: ^9.0.0
  photo_manager: 3.7.1

  rikko_flutter_core:
    path: packages/rikko_flutter_core
  rikko_flutter_pdf:
    path: packages/rikko_flutter_pdf
  rikko_flutter_pdfviewer:
    path: packages/rikko_flutter_pdfviewer
  rikko_pdfviewer_platform_interface:
    path: packages/rikko_flutter_pdfviewer_platform_interface
  printing: ^5.14.2
  collection: ^1.19.1
  animated_reorderable_list: ^1.3.0
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  path: ^1.9.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  image: ^4.5.4
  open_file: ^3.5.10
  flutter_list_view: ^1.1.29
  pull_to_refresh:
    path: packages/flutter_pulltorefresh

  # Mediation ads
  gma_mediation_liftoffmonetize: 1.2.1
  gma_mediation_meta: 1.3.0
  gma_mediation_mintegral: 1.2.3
  gma_mediation_pangle: 3.0.0
  gma_mediation_unity: 1.6.0
#  gma_mediation_applovin: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.2
  flutter_flavorizr: ^2.4.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  injectable_generator: ^2.9.1
  flutter_gen_runner: ^5.12.0
  hive_ce_generator: ^1.10.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/images/rates/
    - assets/images/logo/
    - assets/images/languages/
    - assets/images/onboarding/
    - assets/fonts/
    - assets/fonts/inter/
    - assets/files/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter_18pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter_18pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter_18pt-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter_18pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter_18pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter_18pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter_18pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter_18pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter_18pt-ExtraBoldItalic.ttf
          weight: 800
          style: italic

flutter_gen:
  output: lib/src/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    outputs:
      class_name: Assets

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/logo.png"
  min_sdk_android: 23
